'use strict';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const label=s=>({social:'Social media',announcement:'Announcement',audiobook:'Audiobook',middle:'Middle aged',older:'Older',unclassified:'Not classified'}[s]||s.charAt(0).toUpperCase()+s.slice(1));
const nameOf=id=>voices?.find(v=>v.ShortName===id)?.Name||(id.includes('_')?id.split('_').slice(1).join(' ').replace(/\b\w/g,c=>c.toUpperCase()):id.replace(/^[a-z]{2,3}-[A-Z]{2}-/,'').replace('Neural','').replace('Multilingual',' Multilingual'));
const duration=n=>`${Math.floor(Math.round(n)/60)}:${String(Math.round(n)%60).padStart(2,'0')}`;
const defaults=engine=>({engine,voice:engine==='edge'?'en-US-AndrewNeural':engine==='kitten'?'Jasper':engine==='piper'?'en_US-hfc_female-medium':engine==='chatterbox'?'builtin':'af_heart',speed:.8,pitch:engine==='edge'?-5:0,volume:0,export_format:'mp3_44100_192',normalize:true,output_gain:0,paragraph_pause:0,subtitle_width:42,subtitle_seconds:6,seed:12345,device:'cpu',live_preview:false,blend:[],locale:'en-US',temperature:.8,top_p:.95,top_k:1000,repetition_penalty:1.2});
let state={engine:'edge',settings:{edge:defaults('edge'),kokoro:defaults('kokoro'),kitten:defaults('kitten'),piper:defaults('piper'),chatterbox:defaults('chatterbox')},text:'',title:'',batch:false,autoplay:true,imported:[],retryId:null,resumeAfterEdit:false};
let voices=[],caps={},uses=[],jobs=[],paused=false,gender='all',locale='en-US',seen=null,polling=false,previewBusy=false,voiceRequest=0,tagVoice=null,languageFocus=-1,toastTimer;
const selectedJobs=new Set();
let liveSession=null;
let mergeBusy=false;
let bulkDeleteBusy=false;
try{const saved=JSON.parse(localStorage.getItem('stillwater-v2')||'null');if(saved){state={...state,...saved,settings:{edge:{...defaults('edge'),...saved.settings?.edge},kokoro:{...defaults('kokoro'),...saved.settings?.kokoro},kitten:{...defaults('kitten'),...saved.settings?.kitten},piper:{...defaults('piper'),...saved.settings?.piper},chatterbox:{...defaults('chatterbox'),...saved.settings?.chatterbox}}};}else{const old=JSON.parse(localStorage.getItem('stillwater-draft')||'null');if(old){state.text=old.text||'';state.title=old.title||'';state.batch=!!old.batch;state.autoplay=old.autoplay!==false;state.settings.edge={...defaults('edge'),...old};}}if(localStorage.getItem('stillwater-theme')==='dark')document.body.classList.add('dark');}catch{}
const active=()=>state.settings[state.engine];
function notify(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,6500);}
async function api(path,body){const r=await fetch(path,body===undefined?{cache:'no-store'}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});let data;try{data=await r.json();}catch{throw Error(`Request failed (${r.status}).`);}if(!r.ok)throw Error(data.error||`Request failed (${r.status}).`);return data;}
function persist(){state.text=$('#script').value;state.title=$('#title').value;state.batch=$('#batch').checked;state.autoplay=$('#autoplay').checked;try{localStorage.setItem('stillwater-v2',JSON.stringify(state));$('.saved-mark').textContent='● Draft saved';}catch{$('.saved-mark').textContent='Draft not saved';}}
function pieces(){return $('#script').value.split(/^[ \t]*(?:\*\*|__)?[ \t]*-{3,}[ \t]*(?:\*\*|__)?[ \t]*\r?$/m).map(t=>t.trim()).filter(Boolean);} 
function stats(){const text=$('#script').value,spoken=text.replace(/\[\s*[1-5]\s*s\s+silence\s*\]/gi,' '),words=spoken.trim()?spoken.trim().split(/\s+/).length:0;const pauses=[...text.matchAll(/\[\s*([1-5])\s*s\s+silence\s*\]/gi)].reduce((n,m)=>n+Number(m[1]),0);const paragraphPauses=(text.match(/\n\s*\n/g)||[]).length*active().paragraph_pause;const count=pieces().length;$('#word-count').textContent=`${words.toLocaleString()} words · ~${duration(words/(175*active().speed)*60+pauses+paragraphPauses)} audio${count>1?' · '+count+' separate scripts':''}`;$('#batch-help').hidden=!$('#batch').checked&&count<2;$('#generate').textContent=state.retryId?'↻ Save changes & retry':count>1?`＋ Add ${count} scripts to queue`:'＋ Add to generation queue';persist();}
const controls={'pitch':'pitch','volume':'volume','export-format':'export_format','output-gain':'output_gain','paragraph-pause':'paragraph_pause','subtitle-width':'subtitle_width','subtitle-seconds':'subtitle_seconds','seed':'seed','device':'device','speed':'speed','temperature':'temperature','top-p':'top_p','top-k':'top_k','repetition-penalty':'repetition_penalty'};
function readControls(){const s=active();for(const[id,key]of Object.entries(controls)){s[key]=['device','export_format'].includes(key)?$('#'+id).value:Number($('#'+id).value);}s.normalize=$('#normalize').checked;s.live_preview=$('#live-preview').checked;s.engine=state.engine;}
function paintRanges(){$$('input[type=range]').forEach(r=>r.style.setProperty('--fill',((Number(r.value)-Number(r.min))/(Number(r.max)-Number(r.min))*100)+'%'));const s=active();$('#speed-value').textContent=s.speed.toFixed(2)+'×';$('#pitch-value').textContent=(s.pitch>0?'+':'')+s.pitch+' Hz';$('#volume-value').textContent=(s.volume>0?'+':'')+s.volume+'%';$('#output-gain-value').textContent=(s.output_gain>0?'+':'')+s.output_gain+' dB';$('#paragraph-pause-value').textContent=s.paragraph_pause+' s';$$('[data-speed]').forEach(b=>{const on=Number(b.dataset.speed)===s.speed;b.classList.toggle('active',on);b.setAttribute('aria-pressed',on);});$('#locked-voice').textContent=`${nameOf(s.voice)}${s.blend.length?' blend':''} · ${s.speed.toFixed(2)}×`;}
function renderBlend(){const s=active(),same=voices.filter(v=>v.ShortName[0]===s.voice[0]);$('#blend-rows').innerHTML=s.blend.map((entry,i)=>`<div class="blend-row"><select aria-label="Blend voice ${i+1}" data-blend-index="${i}" ${i===0?'disabled':''}>${same.map(v=>`<option value="${esc(v.ShortName)}" ${v.ShortName===entry.voice?'selected':''}>${esc(nameOf(v.ShortName))} · ${esc(v.Gender)}</option>`).join('')}</select><input type="number" aria-label="Weight for blend voice ${i+1}" min="1" max="1000" value="${entry.weight}" data-weight-index="${i}"><button data-remove-blend="${i}" aria-label="Remove blend voice ${i+1}" ${i===0?'disabled':''}>×</button></div>`).join('');}
function chosen(){const s=active(),v=voices.find(v=>v.ShortName===s.voice);$('#chosen-name').textContent=nameOf(s.voice)+(s.blend.length?' blend':'');$('#chosen-avatar').textContent=nameOf(s.voice)[0];$('#chosen-details').textContent=v?`${v.LocaleName||v.Locale} · ${v.Gender}`:'Choose a voice from the library';paintRanges();}
function applyControls(){const s=active();$('#engine').value=state.engine;$('#speed').max=state.engine==='kokoro'?2:1;for(const[id,key]of Object.entries(controls))$('#'+id).value=s[key];$('#normalize').checked=s.normalize;$('#live-preview').checked=!!s.live_preview;$('#edge-settings').hidden=state.engine!=='edge';$('#kokoro-settings').hidden=state.engine!=='kokoro';$('#chatterbox-settings').hidden=state.engine!=='chatterbox';$('#speed-max-label').textContent=state.engine==='kokoro'?'Faster · 2.0×':'Natural · 1.0×';const speeds=state.engine==='kokoro'?[.5,.6,.7,.8,.9,1,1.25,1.5,2]:[.5,.6,.7,.8,.9,1];$('#speed-presets').innerHTML=speeds.map(n=>`<button data-speed="${n}" aria-pressed="${n===s.speed}">${n.toFixed(n%1===.25?2:1)}×</button>`).join('');$('#source-quality').textContent=caps[state.engine]?.source||'';$('#timing-note').textContent=caps[state.engine]?.timing||'';$('#library-engine').textContent=(state.engine==='kokoro'?'Kokoro 82M · local model':'Microsoft Edge · online service')+' · select a voice or preview it';renderBlend();chosen();stats();}
async function loadVoices(refresh=false){const request=++voiceRequest,engine=state.engine;$('#choose-voice').disabled=true;$('#generate').disabled=true;try{const response=await api((refresh?'/api/voices/refresh':'/api/voices')+'?engine='+engine,refresh?{}:undefined);if(request!==voiceRequest)return;voices=response.voices;await attachSavedAuditions();if(request!==voiceRequest)return;caps=response.capabilities;uses=response.uses;$('#export-format').innerHTML=Object.entries(response.formats).map(([k,v])=>`<option value="${k}">${esc(v)}</option>`).join('');$('#use-filter').innerHTML='<option value="">All uses & styles</option>'+uses.map(u=>`<option value="${u}">${label(u)}</option>`).join('');const s=active();if(voices.length&&!voices.some(v=>v.ShortName===s.voice)){s.voice=voices.find(v=>v.Locale==='en-US')?.ShortName||voices[0].ShortName;s.blend=[];}locale=s.locale||voices.find(v=>v.ShortName===s.voice)?.Locale||'';setLanguage(locale);$('#banner').hidden=!response.warning;$('#banner').textContent=response.warning||'';if(engine==='kokoro'&&!caps.kokoro.ready){$('#banner').hidden=false;$('#banner').textContent='Kokoro model files are not ready. Run the model setup before generating.';}if(engine==='chatterbox'&&!caps.chatterbox.ready){$('#banner').hidden=false;$('#banner').textContent='Chatterbox Nano files are not ready. Run the Chatterbox model setup before generating.';}$('#connection').textContent=`● ${engine==='kokoro'?'Kokoro local':engine==='chatterbox'?'Chatterbox Nano local':'Edge online'} · ${voices.length} voices`;applyControls();renderVoices();}finally{if(request===voiceRequest){$('#choose-voice').disabled=false;$('#generate').disabled=false;}}}
const availabilityAwareLoadVoices=loadVoices;
loadVoices=async function(refresh=false){
  await availabilityAwareLoadVoices(refresh);
  for(const option of $('#engine').options){
    option.dataset.originalLabel ||= option.textContent.replace(/ · Unavailable on this server$/,'');
    const capability=caps[option.value],available=capability?.ready!==false;
    option.textContent=option.dataset.originalLabel+(available?'':' · Unavailable on this server');
  }
  const capability=caps[state.engine],available=capability?.ready!==false;
  $('#choose-voice').disabled=!available;
  $('#generate').disabled=!available;
  if(!available){
    $('#banner').hidden=false;
    $('#banner').textContent=`${capability?.name||state.engine} is unavailable on this server. ${capability?.reason||'This engine is not installed.'}`;
    $('#connection').textContent=`● ${capability?.name||state.engine} unavailable`;
  }
};
function locales(){const map=new Map(voices.map(v=>[v.Locale,v.LocaleName||v.Locale]));return [{id:'',name:'All languages & regions'},...[...map].map(([id,name])=>({id,name})).sort((a,b)=>a.name.localeCompare(b.name))];}
function setLanguage(id){locale=id;active().locale=id;$('#language-search').value=locales().find(l=>l.id===id)?.name||'All languages & regions';$('#language-options').hidden=true;$('#language-search').setAttribute('aria-expanded','false');languageFocus=-1;}
function languageMenu(){const q=$('#language-search').value.toLowerCase();const list=locales().filter(l=>l.name.toLowerCase().includes(q)||l.id.toLowerCase().includes(q));$('#language-options').innerHTML=list.map((l,i)=>`<button type="button" role="option" id="lang-option-${i}" aria-selected="${l.id===locale}" data-locale="${l.id}">${esc(l.name)}</button>`).join('')||'<p class="hint">No matching language.</p>';$('#language-options').hidden=false;$('#language-search').setAttribute('aria-expanded','true');languageFocus=-1;}
function renderVoices(){const q=$('#voice-search').value.trim().toLowerCase(),use=$('#use-filter').value,age=$('#age-filter').value;const filtered=voices.filter(v=>(!locale||v.Locale===locale)&&(gender==='all'||v.Gender===gender)&&(!use||v.Uses.includes(use))&&(!age||v.Age===age)&&JSON.stringify(v).toLowerCase().includes(q));$('#voice-count').textContent=`${filtered.length} voices`;$('#voice-list').innerHTML=filtered.map(v=>`<article class="voice-card ${v.ShortName===active().voice?'selected':''}"><button class="voice-select" data-voice="${esc(v.ShortName)}" aria-pressed="${v.ShortName===active().voice}"><span class="avatar">${esc(nameOf(v.ShortName)[0])}</span><span><span class="voice-name">${esc(nameOf(v.ShortName))}</span><span class="voice-details">${esc(v.Gender)} · ${esc(v.Locale)}${v.Age!=='unclassified'?' · '+label(v.Age):''}</span></span></button><div class="voice-tags">${v.Uses.slice(0,3).map(u=>`<span>${label(u)}</span>`).join('')||'<span>Explore this voice</span>'}</div><div class="voice-card-actions"><button data-preview="${esc(v.ShortName)}" aria-label="Preview ${esc(nameOf(v.ShortName))}" >▷ Preview</button><button data-tags="${esc(v.ShortName)}">Edit tags</button></div></article>`).join('')||'<div class="empty"><h3>No matching voices.</h3><p>Try fewer filters. Age tags may be unclassified; you can add your own tags.</p></div>';paintPreviewButtons();}
function openLibrary(){renderVoices();$('#voice-library').showModal();}
function resetFilters(){gender='all';$('#use-filter').value='';$('#age-filter').value='';$('#voice-search').value='';setLanguage('');$$('[data-gender]').forEach(b=>b.classList.toggle('active',b.dataset.gender==='all'));renderVoices();persist();}
let previewRequest=0, previewAbort=null, currentPreview=null, soundContext=null;
function paintPreviewButtons(){
  const p=currentPreview;
  $$('[data-preview]').forEach(b=>{
    const matches=p?.library&&p.engine===state.engine&&p.voice===b.dataset.preview;
    const playing=matches&&!p.loading&&!p.player.paused&&!p.player.ended;
    b.textContent=matches&&p.loading?'◌ Loading…':playing?'Ⅱ Pause':'▷ Preview';
    b.setAttribute('aria-label',`${playing?'Pause':'Preview'} ${nameOf(b.dataset.preview)}`);
    b.setAttribute('aria-pressed',String(!!playing));
    b.classList.toggle('is-playing',!!playing);
  });
  const playing=p&&!p.library&&!p.loading&&!p.player.paused&&!p.player.ended;
  $('#preview-script').textContent=p&&!p.library&&p.loading?'◌ Preparing preview…':playing?'Ⅱ Pause preview':'▷ Preview script';
}
function stopPreview(){
  ++previewRequest;previewAbort?.abort();previewAbort=null;previewBusy=false;
  if(currentPreview){currentPreview.player.pause();currentPreview.player.removeAttribute('src');currentPreview.player.load();}
  currentPreview=null;paintPreviewButtons();
}
async function preview(voice,text,library=false){
  const signature=JSON.stringify({engine:state.engine,voice,text:text||'',speed:active().speed,...(!library?active():{})});
  if(currentPreview?.signature===signature){
    if(currentPreview.loading){stopPreview();return;}
    const player=currentPreview.player;
    if(!player.paused)player.pause();
    else {if(player.ended)player.currentTime=0;await player.play().catch(()=>{currentPreview.message.textContent='Preview ready. Press the audio player’s play button to allow sound.';});}
    paintPreviewButtons();return;
  }
  stopPreview();liveSession=null;$$('audio').forEach(a=>a.pause());
  const request=previewRequest, controller=new AbortController();previewAbort=controller;previewBusy=true;
  const player=library?$('#library-player'):$('#preview-player'),message=library?$('#library-preview-label'):$('#preview-label');
  if(!library)$('#preview-box').hidden=false;
  player.hidden=true;
  currentPreview={voice,engine:state.engine,signature,library,player,message,loading:true};
  message.textContent=`Preparing ${nameOf(voice)} · ${active().speed.toFixed(2)}×${['kokoro','chatterbox'].includes(state.engine)?' · the local model may take a moment…':'…'}`;
  paintPreviewButtons();
  try{
    const job={...active(),engine:state.engine,voice,text:text||'',audition:library,blend:library?[]:active().blend};
    const saved=library&&voices.find(v=>v.ShortName===voice)?.AuditionURL;
    let result;
    if(saved){result={url:saved,voice,engine:state.engine,playback_rate:job.speed,sample_language:voices.find(v=>v.ShortName===voice)?.AuditionLanguage};}
    else{
      const response=await fetch('/api/preview',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(job),signal:controller.signal});
      result=await response.json();if(!response.ok)throw Error(result.error||'The voice service could not prepare this preview.');
    }
    if(request!==previewRequest)return;
    if(result.voice!==voice||result.engine!==job.engine)throw Error('The preview returned a different voice. Please try again.');
    currentPreview.loading=false;player.src=result.url;player.playbackRate=result.playback_rate||1;player.preservesPitch=true;player.hidden=false;player.muted=false;player.volume=1;
    message.textContent=`${nameOf(voice)} · ${job.speed.toFixed(2)}× · ${result.playback_rate?'instant voice sample · playback speed':library?'original voice, without a blend':'your script settings'}${library&&result.sample_language==='en'&&!voice.startsWith('en-')&&job.engine==='edge'?' · English sample':''}`;
    await player.play().catch(e=>{if(request===previewRequest&&e.name!=='AbortError')message.textContent='Preview ready. Press the player’s play button to allow sound.';});
  }catch(e){if(request===previewRequest&&e.name!=='AbortError'){message.textContent='Preview could not play. '+(e.message==='Failed to fetch'?'Check that the studio is running, then try again.':e.message);currentPreview=null;}}
  finally{if(request===previewRequest){previewBusy=false;previewAbort=null;if(currentPreview)currentPreview.loading=false;paintPreviewButtons();}}
}
for(const id of ['library-player','preview-player']){
  const player=$('#'+id);
  for(const event of ['playing','pause','ended','emptied'])player.addEventListener(event,paintPreviewButtons);
  player.addEventListener('error',()=>{if(currentPreview?.player===player&&player.getAttribute('src')){currentPreview.message.textContent='The audio file could not be played. Click Preview again to regenerate it.';currentPreview=null;paintPreviewButtons();}});
}
$('#voice-library').addEventListener('close',()=>{if(currentPreview?.library)stopPreview();});
const auditionWarmups=new Map();
async function attachSavedAuditions(){
  try{
    const response=await fetch('/static/auditions.json',{cache:'no-cache'});
    if(!response.ok)return;
    const manifest=await response.json();
    for(const voice of voices){const sample=manifest[state.engine+':'+voice.ShortName];if(sample){voice.AuditionURL=sample.url;voice.AuditionLanguage=sample.language;}}
  }catch{}
}
$('#voice-list').addEventListener('pointerover',e=>{
  const button=e.target.closest('[data-preview]');
  const url=button&&voices.find(v=>v.ShortName===button.dataset.preview)?.AuditionURL;
  if(!url||auditionWarmups.has(url))return;
  const audio=new Audio(url);audio.preload='auto';auditionWarmups.set(url,audio);
  if(auditionWarmups.size>12){const first=auditionWarmups.keys().next().value;auditionWarmups.get(first).removeAttribute('src');auditionWarmups.delete(first);}
});
$('#sound-test').onclick=async()=>{
  try{
    $$('audio').forEach(a=>a.pause());
    soundContext ||= new (window.AudioContext||window.webkitAudioContext)();await soundContext.resume();
    const tone=soundContext.createOscillator(),gain=soundContext.createGain();
    tone.frequency.value=523;gain.gain.setValueAtTime(0,soundContext.currentTime);gain.gain.linearRampToValueAtTime(.07,soundContext.currentTime+.08);gain.gain.linearRampToValueAtTime(0,soundContext.currentTime+.9);
    tone.connect(gain);gain.connect(soundContext.destination);tone.start();tone.stop(soundContext.currentTime+1);
    $('#library-preview-label').textContent='Test tone played. If it is silent too: unmute this browser tab and check Windows Volume mixer → browser volume and output device.';
  }catch{ $('#library-preview-label').textContent='The browser blocked sound. Allow sound for this site, then press Test sound again.'; }
};
async function submit(){const texts=pieces();if(!texts.length)return notify('Write or import a script first.');if(texts.length>50)return notify('Add up to 50 scripts at a time.');if(!voices.length)return notify('Load the voice list before generating.');readControls();const title=$('#title').value.trim();const payload=texts.map(text=>({...active(),engine:state.engine,text,title:state.imported.find(c=>c.text.trim()===text)?.title||title}));$('#generate').disabled=true;try{if(state.retryId){if(payload.length!==1)throw Error('Edit one failed script at a time. Remove separator lines when editing a single queued script.');await api('/api/jobs/'+state.retryId,{action:'retry',job:payload[0]});state.retryId=null;if(state.resumeAfterEdit)await api('/api/queue',{paused:false});notify('Changes saved. The original script retries before the next one.');}else{await api('/api/jobs',{jobs:payload});notify(`${payload.length} script${payload.length>1?'s':''} added as numbered parts under one title.`);}$('#script').value='';$('#title').value='';state.imported=[];stats();await poll();}catch(e){notify(e.message);}finally{$('#generate').disabled=false;}}
function jobHTML(job){const activeJob=['queued','running','retrying'].includes(job.status),status={queued:'Waiting',running:'Generating',retrying:'Retrying',completed:'Ready',cancelled:'Cancelled'}[job.status],engine={edge:'Edge',kokoro:'Kokoro',kitten:'Kitten',piper:'Piper',chatterbox:'Chatterbox Nano'}[job.engine]||job.engine;const files=job.files||['mp3','srt','vtt'];return `<div class="job-top">${job.status==='completed'?`<input type="checkbox" data-select-job="${job.id}" aria-label="Select part ${job.part_number} of ${esc(job.group_title||job.title)}" ${selectedJobs.has(job.id)?'checked':''}>`:''}<h3><span class="part-label">Part ${job.part_number||1}</span></h3><span class="status">${status}</span></div><p class="job-meta">${engine} · ${esc(nameOf(job.voice))}${job.blend?.length?' blend':''} · ${job.speed.toFixed(2)}×${job.engine==='edge'?` · ${job.pitch>0?'+':''}${job.pitch} Hz`:''}${job.duration?' · '+duration(job.duration):''}</p><p class="job-script">${esc(job.text)}</p>${job.status==='running'?`<div class="progress"><div style="width:${Math.max(3,job.progress*100)}%"></div></div><p class="job-meta">${job.progress?'Rendering · '+Math.round(job.progress*100)+'%':'Preparing speech…'} · attempt ${job.attempts}</p>`:''}${job.status==='retrying'?`<p class="job-error">${esc(job.error)}</p><p class="retry-countdown"></p>`:''}${job.status==='completed'?`<audio controls preload="metadata" src="/files/${job.id}.mp3"></audio><div class="downloads">${['mp3','wav','srt','vtt'].filter(ext=>files.includes(ext)).map(ext=>`<a href="/files/${job.id}.${ext}?download=1" download>↓ ${ext.toUpperCase()}</a>`).join('')}<a href="/api/archive?ids=${job.id}" download>↓ ZIP</a></div>`:''}<div class="job-actions">${job.status==='running'&&job.live_preview?'<button data-action="live">Listen live</button>':''}${job.status==='retrying'?'<button data-action="retry">Retry now</button><button data-action="edit">Edit & fix</button>':''}${activeJob?'<button data-action="cancel" class="cancel">Cancel script</button>':'<button data-action="reuse">Use script again</button>'}</div>`;}
const baseJobHTML=jobHTML;
jobHTML=job=>baseJobHTML(job).replace('<button data-action="reuse">Use script again</button>','<button data-action="reuse">Use script again</button><button data-action="delete" class="delete-recording">Delete recording</button>');
function selectedActions(){const chosen=jobs.filter(job=>selectedJobs.has(job.id)&&job.status==='completed'),seconds=chosen.reduce((sum,job)=>sum+Number(job.duration||0),0),identities=new Set(chosen.map(job=>JSON.stringify([job.engine,job.voice,job.blend||[]]))),valid=chosen.length>=2&&seconds<=18000&&identities.size===1;$('#selected-actions').hidden=!chosen.length;$('#selected-summary').textContent=`${chosen.length} recording${chosen.length===1?'':'s'} selected · ${duration(seconds)}`;$('#selected-duration').textContent=seconds>18000?'Over the current 5-hour limit. Select fewer parts.':identities.size>1?'Select parts made with the same engine and voice.':chosen.length<2?'Choose at least one more part to merge.':'Ready: one MP3 + one SRT + one VTT, in queue order.';$('#download-selected').textContent=`Download ${chosen.length} original${chosen.length===1?'':'s'} · ZIP`;$('#delete-selected').textContent=bulkDeleteBusy?'Deleting…':`Delete ${chosen.length} recording${chosen.length===1?'':'s'}`;$('#delete-selected').disabled=!chosen.length||bulkDeleteBusy;$('#download-selected').disabled=bulkDeleteBusy;$('#merge-selected').disabled=!valid||mergeBusy||bulkDeleteBusy;}
const groupNodes=new Map();
function renderJobs(){const pending=jobs.filter(j=>['queued','running','retrying'].includes(j.status)),ready=jobs.filter(j=>j.status==='completed'),root=$('#jobs');$('#nav-count').textContent=ready.length;$('#queue-count').textContent=`${ready.length} ready`;$('#queue-status').textContent=paused?'Paused. The current generation can finish.':pending.some(j=>j.status==='retrying')?'Retrying the first script. Later scripts are waiting.':pending.length?`${pending.length} script${pending.length>1?'s':''} in queue`:'Your queue is ready.';$('#pause').textContent=paused?'▷ Resume queue':'Ⅱ Pause queue';$('#download-all').disabled=!ready.length;if(!jobs.length){groupNodes.clear();root.innerHTML='<div class="empty"><span>≋</span><h3>Your next recording starts here.</h3><p>Add a script to the queue. We’ll keep its voice, pace, and settings together.</p></div>';selectedActions();return;}root.querySelector('.empty')?.remove();const ordered=[...pending,...jobs.filter(j=>!pending.includes(j)).reverse()],groups=new Map();for(const job of ordered){const title=job.group_title||job.title||'Untitled recording';if(!groups.has(title))groups.set(title,[]);groups.get(title).push(job);}for(const [title,items] of groups){items.sort((a,b)=>(a.part_number||1)-(b.part_number||1));let group=groupNodes.get(title);if(!group){group=document.createElement('section');group.className='recording-group';group.innerHTML='<header><div><span class="group-kicker">RECORDING SERIES</span><h3></h3></div><span class="group-count"></span></header><div class="recording-group-list"></div>';groupNodes.set(title,group);}group.querySelector('header h3').textContent=title;group.querySelector('.group-count').textContent=`${items.length} part${items.length===1?'':'s'}`;root.appendChild(group);const list=group.querySelector('.recording-group-list');for(const job of items){let node=document.getElementById('job-'+job.id);if(!node){node=document.createElement('article');node.id='job-'+job.id;node.dataset.id=job.id;}const signature=JSON.stringify([job.status,job.progress,job.attempts,job.group_title,job.part_number,job.voice,job.error]);if(node.dataset.signature!==signature){node.className='job '+job.status;node.innerHTML=jobHTML(job);node.dataset.signature=signature;}if(job.status==='retrying')node.querySelector('.retry-countdown').textContent=`${paused?'Queue paused.':'Retry in '+Math.max(0,Math.ceil(job.next_retry-Date.now()/1000))+'s.'} Attempt ${job.attempts}. Later scripts stay queued.`;list.appendChild(node);}}for(const [title,node] of groupNodes){if(!groups.has(title)){node.remove();groupNodes.delete(title);}}selectedActions();}
async function poll(){if(polling)return;polling=true;try{const response=await api('/api/state');jobs=response.jobs;paused=response.paused;renderJobs();const completed=new Set(jobs.filter(j=>j.status==='completed').map(j=>j.id));continueLive();if(seen&&$('#autoplay').checked&&!liveSession&&!previewBusy&&!$('#voice-library').open){const fresh=[...completed].find(id=>!seen.has(id));if(fresh&&!$$('audio').some(a=>!a.paused))$('#job-'+fresh+' audio')?.play().catch(()=>notify('Your recording is ready. Press play to listen.'));}seen=completed;if(voices.length)$('#connection').textContent=`● ${state.engine==='kokoro'?'Kokoro local':'Edge online'} · ${voices.length} voices`;}catch{$('#connection').textContent='Reconnecting…';}finally{polling=false;}}
function saveDownload(blob,filename){const url=URL.createObjectURL(blob),link=document.createElement('a');link.href=url;link.download=filename;link.click();setTimeout(()=>URL.revokeObjectURL(url),60000);}
function paintMergeProgress(value,stage){const percent=Math.max(0,Math.min(100,Math.round(value*100)));$('#merge-progress').hidden=false;$('#merge-stage').textContent=stage;$('#merge-percent').textContent=percent+'%';$('#merge-fill').style.width=percent+'%';}
async function downloadArchive(ids,merge=false,mega=false){if(mega){mergeBusy=true;selectedActions();paintMergeProgress(0,'Starting merge…');try{const started=await api('/api/exports',{ids});let status=started;while(status.status==='working'){paintMergeProgress(status.progress,status.stage);await new Promise(resolve=>setTimeout(resolve,500));status=await api('/api/exports/'+started.id);}if(status.status==='failed')throw Error(status.error||'The mega recording could not be created.');paintMergeProgress(1,status.stage);const response=await fetch(status.url);if(!response.ok)throw Error('The completed ZIP could not be downloaded.');saveDownload(await response.blob(),status.filename);notify('Mega recording ready: MP3, SRT and VTT are in one ZIP.');setTimeout(()=>{$('#merge-progress').hidden=true;},5000);}catch(e){paintMergeProgress(0,'Merge stopped');notify(e.message);}finally{mergeBusy=false;selectedActions();}return;}const params=new URLSearchParams();if(ids?.length)params.set('ids',ids.join(','));if(merge)params.set('merge','1');notify(merge?'Combining your recordings and subtitles…':'Preparing your audio and subtitle ZIP…');try{const response=await fetch('/api/archive?'+params);if(!response.ok){let error;try{error=(await response.json()).error;}catch{}throw Error(error||'Download could not be prepared.');}saveDownload(await response.blob(),merge?'Stillwater-combined-recordings.zip':'Stillwater-recordings.zip');notify('ZIP ready. Check your browser downloads.');}catch(e){notify(e.message);}}
async function reuse(job,edit=false){if($('#script').value.trim()&&!confirm('Replace the current draft with this script?'))return;if(edit){state.resumeAfterEdit=!paused;await api('/api/queue',{paused:true});state.retryId=job.id;notify('Queue paused while you edit this script. Save to retry it in place.');}else state.retryId=null;state.engine=job.engine||'edge';state.settings[state.engine]={...defaults(state.engine),...job,locale:voices.find(v=>v.ShortName===job.voice)?.Locale||''};$('#script').value=job.text;$('#title').value=job.group_title||job.title;$('#batch').checked=false;state.imported=[];await loadVoices();stats();$('#composer').scrollIntoView({behavior:'smooth'});$('#script').focus();}
$('#engine').onchange=async e=>{stopPreview();readControls();state.engine=e.target.value;gender='all';$('#age-filter').value='';$('#voice-search').value='';$$('[data-gender]').forEach(b=>b.classList.toggle('active',b.dataset.gender==='all'));persist();try{await loadVoices();}catch(error){notify(error.message);}};
for(const id of Object.keys(controls))$('#'+id).addEventListener('input',()=>{readControls();paintRanges();stats();});$('#normalize').onchange=()=>{readControls();persist();};$('#live-preview').onchange=()=>{readControls();persist();};
$('#speed-presets').onclick=e=>{const b=e.target.closest('[data-speed]');if(b){active().speed=Number(b.dataset.speed);$('#speed').value=active().speed;paintRanges();stats();}};
$$('[data-pause]').forEach(b=>b.onclick=()=>{const input=$('#script'),start=input.selectionStart,end=input.selectionEnd;input.setRangeText(` [${b.dataset.pause}s silence] `,start,end,'end');input.focus();stats();});
['script','title','batch','autoplay'].forEach(id=>$('#'+id).addEventListener('input',stats));
$('#choose-voice').onclick=openLibrary;$('#nav-voices').onclick=openLibrary;$$('[data-close]').forEach(b=>b.onclick=()=>$('#'+b.dataset.close).close());$$('dialog').forEach(d=>d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}}));
$('#language-search').onfocus=()=>{$('#language-search').select();languageMenu();};$('#language-search').oninput=languageMenu;
$('#language-options').onclick=e=>{const b=e.target.closest('[data-locale]');if(b){setLanguage(b.dataset.locale);renderVoices();persist();}};
$('#language-search').onkeydown=e=>{const options=$$('#language-options [data-locale]');if(e.key==='ArrowDown'||e.key==='ArrowUp'){e.preventDefault();if($('#language-options').hidden)languageMenu();languageFocus=Math.max(0,Math.min(options.length-1,languageFocus+(e.key==='ArrowDown'?1:-1)));options.forEach((b,i)=>b.classList.toggle('focused',i===languageFocus));options[languageFocus]?.scrollIntoView({block:'nearest'});$('#language-search').setAttribute('aria-activedescendant',options[languageFocus]?.id||'');}else if(e.key==='Enter'&&options.length){e.preventDefault();options[Math.max(0,languageFocus)]?.click();}else if(e.key==='Escape'){e.stopPropagation();setLanguage(locale);}};
document.addEventListener('click',e=>{if(!e.target.closest('.combobox'))setLanguage(locale);});
$('#gender').onclick=e=>{const b=e.target.closest('[data-gender]');if(b){gender=b.dataset.gender;$$('[data-gender]').forEach(x=>x.classList.toggle('active',x===b));renderVoices();}};
$('#use-filter').onchange=renderVoices;$('#age-filter').onchange=renderVoices;$('#voice-search').oninput=renderVoices;$('#reset-filters').onclick=resetFilters;
$('#refresh-voices').onclick=async()=>{try{await loadVoices(true);notify('Voice library refreshed.');}catch(e){notify(e.message);}};
$('#voice-list').onclick=async e=>{const select=e.target.closest('[data-voice]'),previewButton=e.target.closest('[data-preview]'),tags=e.target.closest('[data-tags]');if(select){active().voice=select.dataset.voice;active().blend=[];chosen();renderBlend();renderVoices();persist();$('#voice-library').close();}if(previewButton)preview(previewButton.dataset.preview,'',true);if(tags){tagVoice=tags.dataset.tags;const v=voices.find(v=>v.ShortName===tagVoice);$('#tag-title').textContent=nameOf(tagVoice)+' · listening tags';$('#tag-age').value=v.Age;$('#tag-uses').innerHTML=uses.map(u=>`<label><input type="checkbox" value="${u}" ${v.Uses.includes(u)?'checked':''}>${label(u)}</label>`).join('');$('#tag-dialog').showModal();}};
$('#save-tags').onclick=async()=>{try{await api('/api/voice-tags',{engine:state.engine,voice:tagVoice,age:$('#tag-age').value,uses:$$('#tag-uses input:checked').map(x=>x.value)});const use=$('#use-filter').value;await loadVoices();$('#use-filter').value=use;renderVoices();$('#tag-dialog').close();notify('Listening tags saved for this voice.');}catch(e){notify(e.message);}};
$('#add-blend').onclick=()=>{const s=active();if(s.blend.length>=8)return notify('Blend up to eight voices.');if(!s.blend.length)s.blend.push({voice:s.voice,weight:70});const next=voices.find(v=>v.ShortName[0]===s.voice[0]&&!s.blend.some(x=>x.voice===v.ShortName));if(!next)return notify('No additional voice is available in this language.');s.blend.push({voice:next.ShortName,weight:30});renderBlend();chosen();persist();};
$('#blend-rows').onchange=e=>{if(e.target.dataset.blendIndex!==undefined){active().blend[Number(e.target.dataset.blendIndex)].voice=e.target.value;renderBlend();}persist();};
$('#blend-rows').oninput=e=>{if(e.target.dataset.weightIndex!==undefined){active().blend[Number(e.target.dataset.weightIndex)].weight=Math.max(1,Math.min(1000,Number(e.target.value)||1));persist();}};
$('#blend-rows').onclick=e=>{const b=e.target.closest('[data-remove-blend]');if(b){active().blend.splice(Number(b.dataset.removeBlend),1);if(active().blend.length===1)active().blend=[];renderBlend();chosen();persist();}};
$('#preview-script').onclick=()=>preview(active().voice,pieces()[0]||'');$('#generate').onclick=submit;
$$('[data-preset]').forEach(b=>b.onclick=()=>{const presets=state.engine==='edge'?{deep:['en-US-ChristopherNeural',.8,-12],warm:['en-US-AndrewNeural',.9,-5],soft:['en-US-JennyNeural',.8,-3]}:{deep:['am_michael',.8,0],warm:['af_heart',.9,0],soft:['af_nicole',.8,0]};const [voice,speed,pitch]=presets[b.dataset.preset];if(!voices.some(v=>v.ShortName===voice))return notify('This preset voice is not available. Refresh the voice library.');Object.assign(active(),{voice,speed,pitch,volume:0,blend:[]});applyControls();notify(b.textContent.trim()+' applied. Preview to hear it.');});
$('#reset-settings').onclick=()=>{state.settings[state.engine]=defaults(state.engine);applyControls();notify('This engine’s voice settings were reset.');};
$('#clear').onclick=()=>{if($('#script').value.trim()&&!confirm('Clear this editor draft? Saved recordings are kept.'))return;$('#script').value='';$('#title').value='';state.imported=[];state.retryId=null;stats();};
$('#pause').onclick=async()=>{try{await api('/api/queue',{paused:!paused});await poll();}catch(e){notify(e.message);}};
$('#jobs').onchange=e=>{if(e.target.dataset.selectJob){if(e.target.checked)selectedJobs.add(e.target.dataset.selectJob);else selectedJobs.delete(e.target.dataset.selectJob);selectedActions();}};
$('#jobs').onclick=async e=>{const b=e.target.closest('[data-action]');if(!b)return;const job=jobs.find(j=>j.id===b.closest('.job').dataset.id);if(!job)return;const action=b.dataset.action;try{if(action==='live'){liveSession={id:job.id,index:0,run:job.live?.run||null,playing:false};$('#preview-box').hidden=false;$('#preview-player').pause();continueLive();$('#preview-box').scrollIntoView({behavior:'smooth',block:'center'});return;}if(action==='reuse'||action==='edit'){await reuse(job,action==='edit');return;}b.disabled=true;await api('/api/jobs/'+job.id,{action});await poll();}catch(error){notify(error.message);}finally{b.disabled=false;}};
const regularJobAction=$('#jobs').onclick;
$('#jobs').onclick=async e=>{const button=e.target.closest('[data-action]');if(!button||button.dataset.action!=='delete')return regularJobAction(e);const card=button.closest('.job'),job=jobs.find(item=>item.id===card?.dataset.id);if(!job)return;if(!confirm(`Permanently delete “${job.title}” and its audio, SRT, VTT and ZIP files?`))return;button.disabled=true;card.querySelectorAll('audio').forEach(audio=>{audio.pause();audio.removeAttribute('src');audio.load();});try{await api('/api/jobs/'+job.id,{action:'delete'});selectedJobs.delete(job.id);jobs=jobs.filter(item=>item.id!==job.id);card.remove();if(!jobs.length)$('#jobs').innerHTML='<div class="empty"><span>≋</span><h3>Your next recording starts here.</h3><p>Add a script to the queue. We’ll keep its voice, pace, and settings together.</p></div>';renderJobs();notify('Recording deleted.');}catch(error){notify(error.message);await poll();}finally{button.disabled=false;}};
$('#download-all').onclick=()=>downloadArchive();$('#download-selected').onclick=()=>downloadArchive([...selectedJobs]);$('#merge-selected').onclick=()=>downloadArchive([...selectedJobs],true,true);
$('#delete-selected').onclick=async()=>{const ids=jobs.filter(job=>selectedJobs.has(job.id)&&job.status==='completed').map(job=>job.id),count=ids.length;if(!count)return;if(!confirm(`Permanently delete ${count} selected recording${count===1?'':'s'} and all of their audio and caption files?`))return;bulkDeleteBusy=true;selectedActions();for(const id of ids){const card=$('#job-'+id);card?.querySelectorAll('audio').forEach(audio=>{audio.pause();audio.removeAttribute('src');audio.load();});}try{const result=await api('/api/recordings/delete',{ids});ids.forEach(id=>selectedJobs.delete(id));jobs=jobs.filter(job=>!ids.includes(job.id));renderJobs();notify(`${result.deleted} recording${result.deleted===1?'':'s'} permanently deleted.`);}catch(error){notify(error.message);await poll();}finally{bulkDeleteBusy=false;selectedActions();}};
$('#import-button').onclick=()=>$('#import-dialog').showModal();$('#pick-documents').onclick=()=>$('#import-files').click();
$('#import-files').onchange=async e=>{const files=[...e.target.files];if(!files.length)return;if(files.length>50||files.some(f=>f.size>15*1024*1024)){e.target.value='';return notify('Import up to 50 documents, each under 15 MB.');}$('#import-dialog').close();$('#import-button').disabled=true;try{const imported=[];for(const file of files){notify('Importing '+file.name+'…');const content=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file);});const result=await api('/api/import',{name:file.name,content,split_chapters:$('#split-chapters').checked});imported.push(...result.chapters);}const existing=pieces();const all=[...existing,...imported.map(c=>c.text)];state.imported.push(...imported);$('#script').value=all.join('\n\n---\n\n');$('#batch').checked=all.length>1;if(!existing.length&&all.length===1)$('#title').value=imported[0].title;stats();notify(`${imported.length} script${imported.length>1?'s':''} imported. Review the text, then add to the queue.`);}catch(error){notify(error.message||'Document import failed.');}finally{$('#import-button').disabled=false;e.target.value='';}};
$$('[data-scroll]').forEach(b=>b.onclick=()=>$('#'+b.dataset.scroll).scrollIntoView({behavior:'smooth'}));
$('#theme').onclick=()=>{document.body.classList.toggle('dark');try{localStorage.setItem('stillwater-theme',document.body.classList.contains('dark')?'dark':'light');}catch{}};
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter'&&!$('#generate').disabled&&!$('dialog[open]')){e.preventDefault();submit();}});
document.addEventListener('play',e=>{if(e.target.tagName==='AUDIO'&&e.target!==$('#preview-player'))liveSession=null;if(e.target.tagName==='AUDIO')$$('audio').forEach(a=>{if(a!==e.target)a.pause();});},true);
const originalApplyControls=applyControls;
applyControls=()=>{originalApplyControls();if(['kitten','piper','chatterbox'].includes(state.engine)){$('#speed').max=2;$('#speed-max-label').textContent='Faster · 2.0×';$('#speed-presets').innerHTML=[.5,.6,.7,.8,.9,1,1.25,1.5,2].map(n=>`<button data-speed="${n}" aria-pressed="${n===active().speed}">${n.toFixed(n%1===.25?2:1)}×</button>`).join('');$('#kokoro-settings').hidden=true;const piper=state.engine==='piper',chatterbox=state.engine==='chatterbox';$('#library-engine').textContent=chatterbox?'Chatterbox Nano 110M · local CPU · built-in and cloned voices':piper?'Piper · 22 American voices · fast local CPU':'Kitten Micro 40M · fast local CPU · select a voice or preview it';$('#connection').textContent=`● ${chatterbox?'Chatterbox Nano':piper?'Piper':'Kitten'} local CPU · ${voices.length} voices`;}};
const deleteAwareJobHTML=jobHTML;
jobHTML=job=>['kitten','piper'].includes(job.engine)?deleteAwareJobHTML(job).replace('Edge ·',job.engine==='piper'?'Piper ·':'Kitten ·').replace(' · 0 Hz',''):deleteAwareJobHTML(job);
$$('[data-preset]').forEach(button=>button.onclick=()=>{const presets=state.engine==='edge'?{deep:['en-US-ChristopherNeural',.8,-12],warm:['en-US-AndrewNeural',.9,-5],soft:['en-US-JennyNeural',.8,-3]}:state.engine==='kitten'?{deep:['Jasper',.8,0],warm:['Rosie',.9,0],soft:['Luna',.8,0]}:{deep:['am_michael',.8,0],warm:['af_heart',.9,0],soft:['af_nicole',.8,0]};const [voice,speed,pitch]=presets[button.dataset.preset];if(!voices.some(item=>item.ShortName===voice))return notify('This preset voice is not available. Refresh the voice library.');Object.assign(active(),{voice,speed,pitch,volume:0,blend:[]});applyControls();notify(button.textContent.trim()+' applied. Preview to hear it.');});
$$('[data-preset]').forEach(button=>{const previous=button.onclick;button.onclick=()=>{if(state.engine!=='piper')return previous();const presets={deep:['en_US-hfc_male-medium',.8,0],warm:['en_US-hfc_female-medium',.9,0],soft:['en_US-lessac-high',.8,0]};const [voice,speed,pitch]=presets[button.dataset.preset];Object.assign(active(),{voice,speed,pitch,volume:0,blend:[]});applyControls();notify(button.textContent.trim()+' applied. Preview to hear it.');};});
$$('[data-preset]').forEach(button=>{const previous=button.onclick;button.onclick=()=>{if(state.engine!=='chatterbox')return previous();const settings={deep:{speed:.8,temperature:.7,repetition_penalty:1.25},warm:{speed:.9,temperature:.8,repetition_penalty:1.2},soft:{speed:.8,temperature:.65,repetition_penalty:1.3}}[button.dataset.preset];Object.assign(active(),settings,{pitch:0,volume:0,blend:[]});applyControls();notify(button.textContent.trim()+' applied. Preview to hear it.');};});

if($('#add-clone'))$('#add-clone').onclick=async()=>{const button=$('#add-clone'),file=$('#clone-audio').files[0],name=$('#clone-name').value.trim();if(!name)return notify('Enter a name for the cloned voice.');if(!file)return notify('Choose a clean voice recording first.');if(file.size>15*1024*1024)return notify('Reference audio must be under 15 MB.');button.disabled=true;button.textContent='Preparing voice…';try{const content=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file);});const result=await api('/api/chatterbox/voices',{name,content});await loadVoices();active().voice=result.voice.ShortName;active().blend=[];chosen();renderVoices();persist();$('#clone-name').value='';$('#clone-audio').value='';notify(`${result.voice.Name} is ready. Chatterbox will reuse this reference for every part.`);}catch(error){notify(error.message||'The cloned voice could not be added.');}finally{button.disabled=false;button.textContent='＋ Add cloned voice';}};
$('#script').value=state.text;$('#title').value=state.title;$('#batch').checked=state.batch;$('#autoplay').checked=state.autoplay;$('#engine').value=state.engine;
loadVoices().catch(e=>notify(e.message));poll();setInterval(poll,1500);

function continueLive(){
  if(!liveSession||liveSession.playing)return;
  const job=jobs.find(j=>j.id===liveSession.id);
  if(!job)return;
  if(job.live?.run&&job.live.run!==liveSession.run){liveSession.run=job.live.run;liveSession.index=0;}
  const file=job.live?.files[liveSession.index];
  if(file){
    const player=$('#preview-player');player.src='/api/live/'+job.id+'/'+file;
    liveSession.index++;liveSession.playing=true;
    $('#preview-label').textContent='Live Kokoro preview ? '+nameOf(job.voice)+' ? before audio finishing';
    player.play().catch(e=>{if(e.name!=='AbortError')notify('Live audio is ready. Press play to listen.');});
  }else if(job.status==='completed'){$('#preview-label').textContent='Live preview finished. Your full recording is ready below.';liveSession=null;}
  else if(['retrying','cancelled'].includes(job.status)){$('#preview-label').textContent='Live preview stopped. The recording is '+job.status+'.';liveSession=null;}
  else $('#preview-label').textContent='Waiting for the next Kokoro audio segment?';
}
$('#preview-player').addEventListener('ended',()=>{if(liveSession){liveSession.playing=false;continueLive();}});
