"""Create post CMS table. Revision ID: 0004; Revises: 0003."""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
revision='0004';down_revision='0003';branch_labels=None;depends_on=None
def upgrade():
 op.create_table('posts',sa.Column('title',sa.String(240),nullable=False),sa.Column('slug',sa.String(240),nullable=False),sa.Column('content',sa.Text(),server_default='',nullable=False),sa.Column('excerpt',sa.Text()),sa.Column('featured_image_id',sa.Uuid()),sa.Column('author_id',sa.Uuid(),nullable=False),sa.Column('status',sa.String(20),server_default='draft',nullable=False),sa.Column('seo_title',sa.String(240)),sa.Column('seo_description',sa.String(500)),sa.Column('seo_keywords',postgresql.JSONB(),server_default='[]',nullable=False),sa.Column('canonical_url',sa.String(2048)),sa.Column('og_title',sa.String(240)),sa.Column('og_description',sa.String(500)),sa.Column('og_image_id',sa.Uuid()),sa.Column('robots_index',sa.Boolean(),server_default=sa.text('true'),nullable=False),sa.Column('robots_follow',sa.Boolean(),server_default=sa.text('true'),nullable=False),sa.Column('published_at',sa.DateTime(timezone=True)),sa.Column('created_by',sa.Uuid(),nullable=False),sa.Column('updated_by',sa.Uuid(),nullable=False),sa.Column('deleted_at',sa.DateTime(timezone=True)),sa.Column('deleted_by',sa.Uuid()),sa.Column('id',sa.Uuid(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.text('now()'),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.text('now()'),nullable=False),sa.CheckConstraint("status IN ('draft', 'published', 'trash')",name=op.f('ck_posts_valid_status')),sa.ForeignKeyConstraint(['author_id'],['users.id'],ondelete='RESTRICT',name=op.f('fk_posts_author_id_users')),sa.ForeignKeyConstraint(['created_by'],['users.id'],ondelete='RESTRICT',name=op.f('fk_posts_created_by_users')),sa.ForeignKeyConstraint(['updated_by'],['users.id'],ondelete='RESTRICT',name=op.f('fk_posts_updated_by_users')),sa.ForeignKeyConstraint(['deleted_by'],['users.id'],ondelete='SET NULL',name=op.f('fk_posts_deleted_by_users')),sa.PrimaryKeyConstraint('id',name=op.f('pk_posts')),sa.UniqueConstraint('slug',name=op.f('uq_posts_slug')))
 for c in ('status','published_at','author_id'):op.create_index(f'ix_posts_{c}','posts',[c])
def downgrade():
 for c in ('author_id','published_at','status'):op.drop_index(f'ix_posts_{c}',table_name='posts')
 op.drop_table('posts')
