"""Create categories, tags and post taxonomy links. Revision 0005."""
from alembic import op
import sqlalchemy as sa
revision='0005';down_revision='0004';branch_labels=None;depends_on=None
def taxonomy(name):
 op.create_table(name,sa.Column('name',sa.String(120),nullable=False),sa.Column('slug',sa.String(140),nullable=False),sa.Column('description',sa.Text()),sa.Column('status',sa.String(20),server_default='active',nullable=False),sa.Column('created_by',sa.Uuid(),nullable=False),sa.Column('updated_by',sa.Uuid(),nullable=False),sa.Column('deleted_at',sa.DateTime(timezone=True)),sa.Column('deleted_by',sa.Uuid()),sa.Column('id',sa.Uuid(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.text('now()'),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.text('now()'),nullable=False),sa.CheckConstraint("status IN ('active', 'trash')",name=op.f(f'ck_{name}_valid_status')),sa.ForeignKeyConstraint(['created_by'],['users.id'],ondelete='RESTRICT',name=op.f(f'fk_{name}_created_by_users')),sa.ForeignKeyConstraint(['updated_by'],['users.id'],ondelete='RESTRICT',name=op.f(f'fk_{name}_updated_by_users')),sa.ForeignKeyConstraint(['deleted_by'],['users.id'],ondelete='SET NULL',name=op.f(f'fk_{name}_deleted_by_users')),sa.PrimaryKeyConstraint('id',name=op.f(f'pk_{name}')),sa.UniqueConstraint('slug',name=op.f(f'uq_{name}_slug')));op.create_index(f'ix_{name}_status',name,['status'])
def upgrade():
 taxonomy('categories');taxonomy('tags')
 op.create_table('post_categories',sa.Column('post_id',sa.Uuid(),nullable=False),sa.Column('category_id',sa.Uuid(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.text('now()'),nullable=False),sa.ForeignKeyConstraint(['post_id'],['posts.id'],ondelete='CASCADE',name=op.f('fk_post_categories_post_id_posts')),sa.ForeignKeyConstraint(['category_id'],['categories.id'],ondelete='CASCADE',name=op.f('fk_post_categories_category_id_categories')),sa.PrimaryKeyConstraint('post_id','category_id',name=op.f('pk_post_categories')));op.create_index('ix_post_categories_category_id','post_categories',['category_id'])
 op.create_table('post_tags',sa.Column('post_id',sa.Uuid(),nullable=False),sa.Column('tag_id',sa.Uuid(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.text('now()'),nullable=False),sa.ForeignKeyConstraint(['post_id'],['posts.id'],ondelete='CASCADE',name=op.f('fk_post_tags_post_id_posts')),sa.ForeignKeyConstraint(['tag_id'],['tags.id'],ondelete='CASCADE',name=op.f('fk_post_tags_tag_id_tags')),sa.PrimaryKeyConstraint('post_id','tag_id',name=op.f('pk_post_tags')));op.create_index('ix_post_tags_tag_id','post_tags',['tag_id'])
def downgrade():
 op.drop_index('ix_post_tags_tag_id',table_name='post_tags');op.drop_table('post_tags');op.drop_index('ix_post_categories_category_id',table_name='post_categories');op.drop_table('post_categories')
 for name in ('tags','categories'):op.drop_index(f'ix_{name}_status',table_name=name);op.drop_table(name)
