"""Create menus and hierarchical items. Revision 0008."""
from alembic import op
import sqlalchemy as sa
revision='0008';down_revision='0007';branch_labels=None;depends_on=None
def upgrade():
 op.create_table('menus',sa.Column('name',sa.String(120),nullable=False),sa.Column('slug',sa.String(120),nullable=False),sa.Column('location',sa.String(20),nullable=False),sa.Column('status',sa.String(20),server_default='active',nullable=False),sa.Column('created_by',sa.Uuid(),nullable=False),sa.Column('updated_by',sa.Uuid(),nullable=False),sa.Column('id',sa.Uuid(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.text('now()'),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.text('now()'),nullable=False),sa.CheckConstraint("location IN ('header', 'footer', 'custom')",name=op.f('ck_menus_valid_location')),sa.CheckConstraint("status IN ('active', 'disabled')",name=op.f('ck_menus_valid_status')),sa.ForeignKeyConstraint(['created_by'],['users.id'],ondelete='RESTRICT',name=op.f('fk_menus_created_by_users')),sa.ForeignKeyConstraint(['updated_by'],['users.id'],ondelete='RESTRICT',name=op.f('fk_menus_updated_by_users')),sa.PrimaryKeyConstraint('id',name=op.f('pk_menus')),sa.UniqueConstraint('slug',name=op.f('uq_menus_slug')));op.create_index('ix_menus_location_status','menus',['location','status'])
 op.create_table('menu_items',sa.Column('menu_id',sa.Uuid(),nullable=False),sa.Column('parent_id',sa.Uuid()),sa.Column('label',sa.String(120),nullable=False),sa.Column('url',sa.String(2048)),sa.Column('page_id',sa.Uuid()),sa.Column('position',sa.Integer(),server_default='0',nullable=False),sa.Column('open_in_new_tab',sa.Boolean(),server_default=sa.text('false'),nullable=False),sa.Column('enabled',sa.Boolean(),server_default=sa.text('true'),nullable=False),sa.Column('created_by',sa.Uuid(),nullable=False),sa.Column('updated_by',sa.Uuid(),nullable=False),sa.Column('id',sa.Uuid(),nullable=False),sa.Column('created_at',sa.DateTime(timezone=True),server_default=sa.text('now()'),nullable=False),sa.Column('updated_at',sa.DateTime(timezone=True),server_default=sa.text('now()'),nullable=False),sa.ForeignKeyConstraint(['menu_id'],['menus.id'],ondelete='CASCADE',name=op.f('fk_menu_items_menu_id_menus')),sa.ForeignKeyConstraint(['parent_id'],['menu_items.id'],ondelete='SET NULL',name=op.f('fk_menu_items_parent_id_menu_items')),sa.ForeignKeyConstraint(['page_id'],['pages.id'],ondelete='SET NULL',name=op.f('fk_menu_items_page_id_pages')),sa.ForeignKeyConstraint(['created_by'],['users.id'],ondelete='RESTRICT',name=op.f('fk_menu_items_created_by_users')),sa.ForeignKeyConstraint(['updated_by'],['users.id'],ondelete='RESTRICT',name=op.f('fk_menu_items_updated_by_users')),sa.PrimaryKeyConstraint('id',name=op.f('pk_menu_items')));op.create_index('ix_menu_items_menu_position','menu_items',['menu_id','position']);op.create_index('ix_menu_items_parent_id','menu_items',['parent_id'])
def downgrade():
 op.drop_index('ix_menu_items_parent_id',table_name='menu_items');op.drop_index('ix_menu_items_menu_position',table_name='menu_items');op.drop_table('menu_items');op.drop_index('ix_menus_location_status',table_name='menus');op.drop_table('menus')
